<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thank you for contacting Melbourne Legal Lawyers</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #ffffff;">
    <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="background-color: #ffffff;">
        <tr>
            <td align="center" style="padding: 40px 20px;">
                <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="600" style="max-width: 600px; background-color: #ffffff;">
                    <!-- Logo Section -->
                    <tr>
                        <td align="center" style="padding-bottom: 30px;">
                            <img src="{{ asset('images/MLL - LOGO - WEB.png') }}" alt="Melbourne Legal Lawyers" style="max-width: 200px; height: auto;" />
                        </td>
                    </tr>
                    
                    <!-- Heading -->
                    <tr>
                        <td align="center" style="padding-bottom: 40px;">
                            <h1 style="margin: 0; font-size: 32px; font-weight: 600; color: #333333; letter-spacing: -0.5px;">Thank you for your inquiry</h1>
                        </td>
                    </tr>
                    
                    <!-- Content -->
                    <tr>
                        <td style="padding-bottom: 20px;">
                            <p style="margin: 0 0 20px 0; font-size: 16px; color: #333333; line-height: 1.6;">Dear {{ htmlspecialchars($fullName) }},</p>
                            <p style="margin: 0 0 20px 0; font-size: 16px; color: #333333; line-height: 1.6;">We have received your contact form submission and will get back to you soon.</p>
                            
                            <div style="margin: 30px 0;">
                                <p style="margin: 0 0 10px 0; font-size: 16px; font-weight: 600; color: #333333;">Your inquiry details:</p>
                                <ul style="margin: 0; padding-left: 20px; font-size: 16px; color: #333333; line-height: 1.8;">
                                    <li>Practice Area: {{ htmlspecialchars($practiceArea) }}</li>
                                    <li>Description: {{ htmlspecialchars($description) }}</li>
                                </ul>
                            </div>
                            
                            <p style="margin: 20px 0 0 0; font-size: 16px; color: #333333; line-height: 1.6;">If you have any urgent matters, please call us at <a href="tel:+61312345678" style="color: #0066cc; text-decoration: none;">+61 3 1234 5678</a>.</p>
                        </td>
                    </tr>
                    
                    <!-- Footer -->
                    <tr>
                        <td style="padding-top: 40px; border-top: 1px solid #e5e5e5;">
                            <p style="margin: 0 0 10px 0; font-size: 16px; color: #333333; line-height: 1.6;">Best regards,<br>Melbourne Legal Lawyers</p>
                            <p style="margin: 20px 0 0 0; font-size: 12px; color: #999999; line-height: 1.5;">This email was generated by Melbourne Legal Lawyers Website</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>

